# An example configuration file.
---
APPROACHES:
  my-oracle:  # used in constructing the experiment ID
    NAME: "oracle"
    FLAGS:
      offline_data_planning_timeout: 500.0
      timeout: 500.0
      plan_only_eval: True
      sesame_task_planner: fdopt
ENVS:
  collecting_aluminum_cans-Benevolence_2_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Benevolence_2_int
      behavior_task_list: "[collecting_aluminum_cans]"
      behavior_option_model_eval: True
  throwing_away_leftovers-Ihlen_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Ihlen_1_int
      behavior_task_list: "[throwing_away_leftovers]"
      behavior_option_model_eval: True
  setting_up_candles-Beechwood_0_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Beechwood_0_int
      behavior_task_list: "[setting_up_candles]"
      behavior_option_model_eval: True
  packing_bags_or_suitcase-Merom_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Merom_1_int
      behavior_task_list: "[packing_bags_or_suitcase]"
      behavior_option_model_eval: True
  packing_boxes_for_household_move_or_trip-Ihlen_0_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Ihlen_0_int
      behavior_task_list: "[packing_boxes_for_household_move_or_trip]"
      behavior_option_model_eval: True
  opening_presents-Pomaria_2_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Pomaria_2_int
      behavior_task_list: "[opening_presents]"
      behavior_option_model_eval: True
  assembling_gift_baskets-Rs_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Rs_int
      behavior_task_list: "[assembling_gift_baskets]"
      behavior_option_model_eval: True
  organizing_file_cabinet-Pomaria_0_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Pomaria_0_int
      behavior_task_list: "[organizing_file_cabinet]"
      behavior_option_model_eval: True
  locking_every_window-Rs_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Rs_int
      behavior_task_list: "[locking_every_window]"
      behavior_option_model_eval: True
  packing_car_for_trip-Ihlen_0_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Ihlen_0_int
      behavior_task_list: "[packing_car_for_trip]"
      behavior_option_model_eval: True
  re-shelving_library_books-Pomaria_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Pomaria_1_int
      behavior_task_list: "[re-shelving_library_books]"
      behavior_option_model_eval: True
  storing_food-Beechwood_0_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Beechwood_0_int
      behavior_task_list: "[storing_food]"
      behavior_option_model_eval: True
  organizing_boxes_in_garage-Ihlen_0_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Ihlen_0_int
      behavior_task_list: "[organizing_boxes_in_garage]"
      behavior_option_model_eval: True
  polishing_silver-Wainscott_0_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Wainscott_0_int
      behavior_task_list: "[polishing_silver]"
      behavior_option_model_eval: True
  putting_leftovers_away-Ihlen_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Ihlen_1_int
      behavior_task_list: "[putting_leftovers_away]"
      behavior_option_model_eval: True
  unpacking_suitcase-Ihlen_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Ihlen_1_int
      behavior_task_list: "[unpacking_suitcase]"
      behavior_option_model_eval: True
  putting_away_toys-Ihlen_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Ihlen_1_int
      behavior_task_list: "[putting_away_toys]"
      behavior_option_model_eval: True
  boxing_books_up_for_storage-Benevolence_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Benevolence_1_int
      behavior_task_list: "[boxing_books_up_for_storage]"
      behavior_option_model_eval: True
  packing_adult_s_bags-Benevolence_2_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Benevolence_2_int
      behavior_task_list: "[packing_adult_s_bags]"
      behavior_option_model_eval: True
  sorting_books-Pomaria_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Pomaria_1_int
      behavior_task_list: "[sorting_books]"
      behavior_option_model_eval: True
  clearing_the_table_after_dinner-Benevolence_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Benevolence_1_int
      behavior_task_list: "[clearing_the_table_after_dinner]"
      behavior_option_model_eval: True
  opening_packages-Pomaria_2_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Pomaria_2_int
      behavior_task_list: "[opening_packages]"
      behavior_option_model_eval: True
  laying_tile_floors-Pomaria_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Pomaria_1_int
      behavior_task_list: "[laying_tile_floors]"
      behavior_option_model_eval: True
  bringing_in_wood-Wainscott_0_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Wainscott_0_int
      behavior_task_list: "[bringing_in_wood]"
      behavior_option_model_eval: True
  picking_up_take-out_food-Benevolence_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Benevolence_1_int
      behavior_task_list: "[picking_up_take-out_food]"
      behavior_option_model_eval: True
  loading_the_dishwasher-Pomaria_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Pomaria_1_int
      behavior_task_list: "[loading_the_dishwasher]"
      behavior_option_model_eval: True
  cleaning_freezer-Wainscott_0_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Wainscott_0_int
      behavior_task_list: "[cleaning_freezer]"
      behavior_option_model_eval: True
  cleaning_the_pool-Ihlen_0_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Ihlen_0_int
      behavior_task_list: "[cleaning_the_pool]"
      behavior_option_model_eval: True
  collect_misplaced_items-Merom_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Merom_1_int
      behavior_task_list: "[collect_misplaced_items]"
      behavior_option_model_eval: True
  locking_every_door-Pomaria_0_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Pomaria_0_int
      behavior_task_list: "[locking_every_door]"
      behavior_option_model_eval: True
  putting_dishes_away_after_cleaning-Beechwood_0_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Beechwood_0_int
      behavior_task_list: "[putting_dishes_away_after_cleaning]"
      behavior_option_model_eval: True
  filling_a_Christmas_stocking-Rs_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Rs_int
      behavior_task_list: "[filling_a_Christmas_stocking]"
      behavior_option_model_eval: True
  picking_up_trash-Wainscott_0_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Wainscott_0_int
      behavior_task_list: "[picking_up_trash]"
      behavior_option_model_eval: True
  packing_lunches-Beechwood_0_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Beechwood_0_int
      behavior_task_list: "[packing_lunches]"
      behavior_option_model_eval: True
  cleaning_a_car-Ihlen_0_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Ihlen_0_int
      behavior_task_list: "[cleaning_a_car]"
      behavior_option_model_eval: True
  cleaning_garage-Ihlen_0_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Ihlen_0_int
      behavior_task_list: "[cleaning_garage]"
      behavior_option_model_eval: True
  moving_boxes_to_storage-Merom_0_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Merom_0_int
      behavior_task_list: "[moving_boxes_to_storage]"
      behavior_option_model_eval: True
  packing_food_for_work-Wainscott_0_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Wainscott_0_int
      behavior_task_list: "[packing_food_for_work]"
      behavior_option_model_eval: True
ARGS: {}
FLAGS:  # general flags
  num_train_tasks: 0
  num_test_tasks: 5
START_SEED: 0
NUM_SEEDS: 1
USE_GPU: True
