
# An example configuration file.
---
APPROACHES:
  backchaining:
    NAME: "nsrt_learning"
    FLAGS:
      offline_data_planning_timeout: 500.0
      timeout: 500.0
      sampler_learner: neural
      strips_learner: backchaining
      plan_only_eval: True
      sesame_task_planner: fdopt
ENVS:
  throwing_away_leftovers-Ihlen_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Ihlen_1_int
      behavior_task_list: "[throwing_away_leftovers]"
      behavior_option_model_eval: True
ARGS: {}
FLAGS:  # general flags
  num_train_tasks: 10
  num_test_tasks: 10
START_SEED: 0
NUM_SEEDS: 5
USE_GPU: True